table 'Measures (2)'
	lineageTag: 58a0930f-8559-4df6-8891-f52970643daa

	column Measures
		dataType: string
		lineageTag: 9a60ccf8-5e32-4ae7-9907-45a30d991a8f
		summarizeBy: none
		sourceColumn: Measures

		annotation SummarizationSetBy = Automatic

	measure 'Total Sales' = SUM(FactSales[SalesAmount])
		formatString: "$#,0.00"

	measure 'Total Quantity' = SUM(FactSales[Quantity])

	measure 'Average Unit Price' = DIVIDE([Total Sales], [Total Quantity])
		formatString: "$#,0.00"

	measure 'Sales per Customer' = DIVIDE([Total Sales], DISTINCTCOUNT(DimCustomer[CustomerKey]))
		formatString: "$#,0.00"

	measure '% Sales Share' = DIVIDE([Total Sales], CALCULATE([Total Sales], ALL(DimProduct[Category])))
		formatString: "0.00%"

	partition 'Measures (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

